package(default_visibility = ["//visibility:public"])

cc_library(
    name = "talon_wrapper",
    srcs = [
        "talon_wrapper.cpp",
    ],
    hdrs = ["talon_wrapper.h"],
    deps = [
        "//muan/units",
    ],
    includes = ["."],
)
