package(default_visibility = ["//visibility:public"])

cc_library(
    name = "carriage_canifier",
    srcs = ["carriage_canifier.cpp"],
    hdrs = ["carriage_canifier.h"],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//third_party/phoenixsuite:phoenix",
    ],
)
