package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sp_factory",
    srcs = ["sp_factory.cpp"],
    hdrs = ["sp_factory.h"],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//third_party/phoenixsuite:phoenix",
    ],
)
