package(default_visibility = ["//visibility:public"])

cc_library(
    name = "talon_wrapper",
    srcs = [
        "talon_wrapper.cpp",
        "talon_wrapper.hpp",
    ],
    hdrs = ["talon_wrapper.h"],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//third_party/phoenixsuite:phoenix",
    ],
)
