package(default_visibility = ["//visibility:public"])

cc_library(
    name = "canifier",
    srcs = ["canifier.cpp"],
    hdrs = ["canifier.h"],
    includes = ["."],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//third_party/phoenixsuite:phoenix",
    ],
)
