package(default_visibility = ["//visibility:public"])

cc_library(
    name = "drivetrain",
    srcs = ["drivetrain.cpp"],
    hdrs = ["drivetrain.h"],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//third_party/phoenixsuite:phoenix",
    ],
)
