cc_binary(
    name = "frc1678",
    srcs = [
        "main.cpp",
    ],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//o2018/subsystems:subsystem_runner",
        "//third_party/gflags",
        "//third_party/wpilibsuite:wpilib",
    ],
)
