package(default_visibility = ["//visibility:public"])

cc_library(
    name = "drivetrain",
    srcs = [
        "drivetrain.cpp",
    ],
    hdrs = [
        "drivetrain.h",
    ],
    deps = [
        "//muan/control:drivetrain_model",
    ],
)
