cc_binary(
    name = "frc1678",
    srcs = [
        "main.cpp",
    ],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//third_party/phoenixsuite:phoenix",
        "//third_party/wpilibsuite:wpilib",
    ],
)
